from .base import *

SECRET_KEY = env('DJANGO_SECRET_KEY')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = ['*']

SECURE_HSTS_SECONDS = 60

SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=True
)

SECURE_CONTENT_TYPE_NOSNIFF = env.bool(
    'DJANGO_SECURE_CONTENT_TYPE_NOSNIFF',
    default=True
)
SECURE_SSL_REDIRECT = env.bool(
    'DJANGO_SECURE_SSL_REDIRECT',
    default=False
)
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True

DATABASES['default'] = env.db('DATABASE_URL')

ADMIN_URL = env('DJANGO_ADMIN_URL')

STATIC_ROOT = env('DJANGO_STATIC_ROOT')
STATIC_URL = env('DJANGO_STATIC_URL')

MEDIA_ROOT = env('DJANGO_MEDIA_ROOT')
MEDIA_URL = env('DJANGO_MEDIA_URL')
